services:

  app:
    build: .
    container_name: spring-app
    depends_on:
      - mariadb-app
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb-app:3306/app-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - spring-network

  mariadb-app:
    image: mariadb:11.3
    container_name: mariadb-app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app-db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - spring-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mariadb-app
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb-app
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  mariadb_data:
